arch/urls.py
from django.conf.urls import patterns, include, url
from django.http import HttpResponse

from django.contrib import admin
admin.autodiscover()



urlpatterns = patterns('',
	(r'^robots\.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: /", mimetype="text/plain")),
	url(r'^admin/', include(admin.site.urls)),
	url(r'^', include('results.urls')),
)

results/urls.py
from django.conf.urls import patterns, include, url


from results import views

package_patterns = patterns('',
	url(r'^load_flag/$', views.load, name='load_flag'),
	url(r'^load_bug/$', views.loadBug, name='load_bug'),
	url(r'^edit/$', views.edit, name='edit'),
	url(r'^rebuild/$', views.rebuild, name='rebuild'),
	url(r'^download/$', views.download, name='download'),
	url(r'^detect/$', views.detect, name='detect'),
	url(r'^json/$', views.pkg_json, name='pkg_json'),
	url(r'^log/(?P<build>[0-9]+)/$', views.GetSpecificLog, name='log'),
	url(r'^log/$', views.GetLog, name='log'),
	url(r'^$', views.PackageView, name='package'),
)

urlpatterns = patterns('',
	url(r'^rebuild/$', views.rebuildList),
	url(r'^add/$', views.add),
	url(r'^submit/$', views.submit),
	url(r'^load_json/$', views.loadJSON),
	url(r'^json/$', views.search_json),
	url(r'^(?P<repo>\w+)/(?P<package>[^ /]+)/', include(package_patterns)),
	url(r'^$', views.IndexView.as_view(), name='index'),
)

urlpatterns += patterns('django.contrib.auth.views',
	(r'^login/$',           'login',  {
		'template_name': 'login.html'}),
	(r'^logout/$',          'logout', {
		'template_name': 'logout.html'}),
)

results/models.py
from django.db import models
import codecs


class LogField(models.Field, metaclass=models.SubfieldBase):
	def db_type(self, connection):
		return 'bytea'
	#def to_python(self, value):
	#	if (value):
	#		return codecs.decode(value, 'bz2').decode('utf-8')
	#	else:
	#		return self.get_default()
	#def get_prep_value(self, value):
	#	return codecs.encode(value.encode('utf-8'), 'bz2')

class Result(models.Model):
	package = models.CharField(max_length=200, db_index=True)
	repo = models.ForeignKey('Repo')
	jenkins_id = models.IntegerField(default=0)
	status = models.IntegerField(default=0)
	last_built = models.DateTimeField(auto_now_add = True, db_index=True)
	bug_id = models.IntegerField(default=0)
	flagged = models.BooleanField(default=False)
	arch = models.CharField(max_length=200, blank=True)
	reason = models.IntegerField(default=0)
	new_fail = models.BooleanField(default=False)
	maintainer = models.CharField(max_length=200, default='', blank=True)
	def __str__(self):
		return self.package

class Build(models.Model):
	package = models.ForeignKey('Result')
	length = models.IntegerField(default=0)
	time = models.DateTimeField(auto_now_add = True)
	jenkins_id = models.IntegerField(default=0)
	status = models.IntegerField(default=0)
	reason = models.IntegerField(default=0)
	data = models.IntegerField(default=0)
	size = models.IntegerField(default=0)
	log = LogField(null=True)


class Repo(models.Model):
	name = models.CharField(max_length=200, unique=True)
	bugs_project = models.SmallIntegerField(default=1)
	bugs_category = models.SmallIntegerField(default=2)
	svn_path = models.CharField(max_length=64)
	def __str__(self):
		return self.name

results/views.py
import codecs
import io
import json
import os
import re
import urllib.error
import urllib.parse
import urllib.request
import zipfile
from datetime import datetime

from django import forms
from django.contrib.auth.decorators import login_required
from django.core.files import File
from django.core.urlresolvers import reverse
from django.db.models import Avg
from django.forms import ModelForm
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.template.base import add_to_builtins
from django.views import generic
from django.views.decorators.csrf import csrf_exempt
from django.core.serializers.json import DjangoJSONEncoder

from results.models import Build, Repo, Result
from results.tags import JenkinsURL, Status, Reason

add_to_builtins('results.tags')

make_choice = lambda l: [(str(m), str(m)) for m in l]

class PackageSearchForm(forms.Form):
	repo = forms.MultipleChoiceField(required=False)
	arch = forms.MultipleChoiceField(required=False)
	name = forms.CharField(required=False)
	desc = forms.CharField(required=False)
	q = forms.CharField(required=False)
	sort = forms.CharField(required=False, widget=forms.HiddenInput())
	maintainer = forms.ChoiceField(required=False)
	packager = forms.ChoiceField(required=False)
	flagged = forms.ChoiceField(
		choices=[('', 'All')] + make_choice(['Flagged', 'Not Flagged']),
		required=False)
	status = forms.ChoiceField(
		choices=[('', 'All')] + make_choice(['Success', 'Failure', 'In progress', 'Removed', 'Unbuilt']),
		required=False)
	reason = forms.ChoiceField(
		choices=[('', 'All')] + make_choice(['General', 'Check', 'Source', 'Hash', 'Depends']),
		required=False)
	bug = forms.ChoiceField(
		choices=[('', 'All')] + make_choice(['Yes', 'No']),
		required=False)
	page = forms.CharField(required=False)
	limit = forms.IntegerField(required=False)
	avg_max = forms.IntegerField(required=False)
	avg_min = forms.IntegerField(required=False)
	new_fail = forms.IntegerField(required=False)

	def __init__(self, *args, **kwargs):
		super(PackageSearchForm, self).__init__(*args, **kwargs)
		repos = Repo.objects.all()
		self.fields['repo'].choices = make_choice([repo.name for repo in repos])

@csrf_exempt
def submit(request):
#	if get_client_ip(request) != "127.0.0.1" and not request.user.is_authenticated():
#		return HttpResponse("NO AUTH\n");
	package = request.POST['package']
	repo = request.POST['repo']
	jenkins_id = request.POST['jenkins_id']
	status = int(request.POST['status'])
	if status == 255:
		status = 1
	try:
		r = Result.objects.get(package=package, repo__name=repo)
	except Result.DoesNotExist:
		return HttpResponse("")
	r.jenkins_id = jenkins_id
	r.status = status
	r.last_built = datetime.now()
	r.reason = 0
	r.new_fail = False
	if r.status == 1:
		builds = Build.objects.filter(package=r).order_by('-time')
		if len(builds) and builds[0].status == 0:
			r.new_fail = True
	r.save()
	if r.status != 0:
		detectFailure(r)
	if r.status != 2:
		b = Build()
		b.package = r
		b.length = request.POST['time'];
		b.jenkins_id = request.POST['jenkins_id']
		b.status = status
		b.reason = r.reason
		response = urllib.request.urlopen("%s/consoleText" % JenkinsURL(r.jenkins_id))
		res = response.read()
		b.log = codecs.encode(res, 'bz2')
		#if 'size' in request.POST and request.POST['size'] != None and request.POST['size'] != "":
		#	b.size = request.POST['size']
		b.save()
	return HttpResponse("OK\n")

@csrf_exempt
def add(request):
#	if get_client_ip(request) != "162.243.149.218":
#	return HttpResponse("NO AUTH\n");
	package = request.POST['package']
	repo = request.POST['repo']
	try:
		r = Result.objects.get(package=package, repo__name=repo)
	except Result.DoesNotExist:
		rep = Repo.objects.get(name=repo)
		r = Result(package=package, repo=rep)
		r.status = -1
		r.save()

	return HttpResponse("OK")

def detect(request, repo, package):
	r = Result.objects.get(package=package, repo__name=repo)
	detectFailure(r)

	return HttpResponse("")

def outputLog(b):
	return HttpResponse("<pre>"+codecs.decode(b.log,'bz2').decode('utf-8')+"</pre>")


def GetLog(request, repo, package):
	r = get_object_or_404(Result, package=package, repo__name=repo)

	b = Build.objects.filter(package=r).latest('time')

	return outputLog(b)


def GetSpecificLog(request, repo, package, build):
	r = get_object_or_404(Result, package=package, repo__name=repo)
	b = get_object_or_404(Build, package=r, jenkins_id=build)
	return outputLog(b)

def detectFailure(r):
	response = urllib.request.urlopen("%s/consoleText" % JenkinsURL(r.jenkins_id))
	res = response.read().decode("utf-8")
	if (res.find("A failure occurred in check") != -1):
		r.reason = 2
	elif (res.find("One or more files did not pass the validity check!") != -1):
		r.reason = 6
	elif (res.find("Could not download sources") != -1):
		r.reason = 3
	elif (res.find("failed to install missing dependencies") != -1):
		r.reason = 4
	elif (res.find("End-of-central-directory signature not found") != -1):
		r.reason = 5
	else:
		r.reason = 1
	r.save()


def load(request, repo, package):
	r = Result.objects.get(package=package, repo__name=repo)
	response = None
	try:
		response = urllib.request.urlopen("https://www.archlinux.org/packages/"+r.repo.name+"/"+"x86_64"+"/"+r.package+"/json/")
	except:
		response = urllib.request.urlopen("https://www.archlinux.org/packages/"+r.repo.name+"/"+"any"+"/"+r.package+"/json/")
	res = response.read().decode("utf-8")
	data = json.loads(res)
	processJSON(data)
	if data['flag_date'] != None:
		return HttpResponse('flag')
	else:
		return HttpResponse('no flag')

def loadBug(request, repo, package):
	r = Result.objects.get(package=package, repo__name=repo)
	project = 0
	if repo == "community":
		project = 5
	response = urllib.request.urlopen("https://bugs.archlinux.org/index.php?string="+package+"&project="+str(project)+"&status%5B%5D=open&opened=klusark")
	res = response.read().decode("utf-8")
	m = re.search('/task/([0-9]+)', res)
	if m == None:
		r.bug_id = 0
		r.save()
		return HttpResponse("no bug")
	r.bug_id = int(m.group(0)[6:])
	r.save()
	return HttpResponse("bug")


def buildPackage(repo, package):
	rl = Result.objects.filter(package=package, repo__name=repo)
	rl = rl.annotate(a=Avg('build__length'))
	r = rl[0];
	data = {}
	data['PACKAGE'] = package
	data['REPO'] = repo
	data['token'] = "BUILDTOKEN"
	#if (r.a == None or r.a > 600):
	#	data['NODE'] = 'build1'
	d = urllib.parse.urlencode(data).encode('UTF-8')
	headers = {"Content-type": "application/x-www-form-urlencoded", "Accept": "text/plain"}
	response = urllib.request.urlopen("http://127.0.0.1:8090/job/package/buildWithParameters", d)

@login_required()
def rebuild(request, repo, package):
	buildPackage(repo, package)
	return HttpResponseRedirect(reverse('package', args=(repo, package,)))

def get_client_ip(request):
	x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
	if x_forwarded_for:
		ip = x_forwarded_for.split(',')[0]
	else:
		ip = request.META.get('REMOTE_ADDR')
	return ip

def rebuildList(request):
#	if get_client_ip(request) != "127.0.0.1" and not request.user.is_authenticated():
#		return HttpResponse("NO AUTH\n");
	form = PackageSearchForm(data=request.GET)
	if form.is_valid():
		objs = Result.objects.all();
		objs = filterObjs(form, objs)
		for r in objs:
			buildPackage(r.repo.name, r.package)
		return HttpResponse(" OK\n");
	return HttpResponse("You messed up the form\n");

def filterObjs(form, objs):
	if form.cleaned_data['flagged'] == 'Flagged':
		objs = objs.filter(flagged = 1)
	elif form.cleaned_data['flagged'] == 'Not Flagged':
		objs = objs.filter(flagged = 0)

	if form.cleaned_data['repo']:
		objs = objs.filter(repo__name__in=form.cleaned_data['repo'])

	if form.cleaned_data['status'] == 'Success':
		objs = objs.filter(status = 0)
	elif form.cleaned_data['status'] == 'Failure':
		objs = objs.filter(status = 1)
	elif form.cleaned_data['status'] == 'In progress':
		objs = objs.filter(status = 2)
	elif form.cleaned_data['status'] == 'Removed':
		objs = objs.filter(status = 3)
	elif form.cleaned_data['status'] == 'Unbuilt':
		objs = objs.filter(status = -1)

	if form.cleaned_data['bug'] == 'Yes':
		objs = objs.filter(bug_id__gt = 0)
	elif form.cleaned_data['bug'] == 'No':
		objs = objs.filter(bug_id = 0)

	if form.cleaned_data['reason'] == 'General':
		objs = objs.filter(reason = 1)
	elif form.cleaned_data['reason'] == 'Check':
		objs = objs.filter(reason = 2)
	elif form.cleaned_data['reason'] == 'Source':
		objs = objs.filter(reason = 3)
	elif form.cleaned_data['reason'] == 'Hash':
		objs = objs.filter(reason = 6)
	elif form.cleaned_data['reason'] == 'Depends':
		objs = objs.filter(reason = 4)

	if form.cleaned_data['avg_max'] != None or form.cleaned_data['avg_min'] != None or form.cleaned_data['sort'] == 'avg'or form.cleaned_data['sort'] == '-avg':
		objs = objs.annotate(avg=Avg('build__length'))

	if form.cleaned_data['avg_max'] != None:
		objs = objs.filter(avg__lte=int(form.cleaned_data['avg_max']))

	if form.cleaned_data['avg_min'] != None:
		objs = objs.filter(avg__gte=int(form.cleaned_data['avg_min']))

	if form.cleaned_data['q'] != None:
		objs = objs.filter(package__icontains=form.cleaned_data['q']);

	if form.cleaned_data['new_fail'] != None:
		objs = objs.filter(new_fail=True)

	sort = form.cleaned_data['sort']
	sort_fields = ['last_built', 'avg', 'package', 'repo']
	allowed_sort = list(sort_fields) + ["-" + s for s in sort_fields]
	if sort in allowed_sort:
		objs = objs.order_by(sort)
	else:
		objs = objs.order_by('-last_built')

	limit = 100
	if form.cleaned_data['limit'] != None:
		objs = objs[:int(form.cleaned_data['limit'])]
		limit = int(form.cleaned_data['limit'])


	return objs

class IndexView(generic.ListView):
	template_name = 'index.html'

	paginate_by = 50

	def get(self, request, *args, **kwargs):
		self.form = PackageSearchForm(data=request.GET)
		return super(IndexView, self).get(request, *args, **kwargs)

	def get_queryset(self):

results/templates/base.html
<!DOCTYPE html>
<html>
<head>
<title>Arch-CI</title>
<style>
.filter-criteria div {
float: left;
margin-right: 1.65em;
}
</style>
</head>
<body>
{% block content %}{% endblock %}
</body>
</html>

results/templates/edit.html
{% extends "base.html" %}

{% block content %}
<form action="{% url 'edit' r.repo.name r.package %}" method="post">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Submit" />
</form>
{% endblock %}

results/templates/index.html
{% extends "base.html" %}

{% block content %}
<div id="pkglist-search" class="box filter-criteria">

    <form id="pkg-search" method="get" action="{% url 'index' %}">
        <p>{{ search_form.sort }}</p>
        {{ search_form.non_field_errors }}
        <fieldset>
            <legend>Enter search criteria</legend>
            <div>{{ search_form.repo.errors }}
                <label for="id_repo" title="Limit results to a specific respository">
                    Repository</label>{{ search_form.repo }}</div>
            <div>{{ search_form.q.errors }}
                <label for="id_q" title="Enter keywords as desired">
                    Keywords</label>{{ search_form.q }}</div>
            <div>{{ search_form.flagged.errors }}
                <label for="id_flagged" title="Limit results based on out-of-date status">
                    Flagged</label>{{ search_form.flagged }}</div>
            <div>{{ search_form.status.errors }}
                <label for="id_status" title="Limit results based on build status">
                    Status</label>{{ search_form.status }}</div>
            <div>{{ search_form.reason.errors }}
                <label for="id_reason" title="Limit results based on build failure reason">
                    Reason</label>{{ search_form.reason }}</div>
            <div>{{ search_form.bug.errors }}
                <label for="id_bug" title="Limit results based on bugs">
                    Bug Report</label>{{ search_form.bug }}</div>
            <div ><label>&nbsp;</label><input title="Search for packages using this criteria"
                type="submit" value="Search" /></div>
        </fieldset>
    </form>

</div><!-- #pkglist-search -->
{% if object_list %}
    <table>
	<tr>
	<th>Repo</th>
	<th><a href="?{% buildsortqs "package" %}" title="Sort packages by pacakge name">Name</a></th>
	<th>Status</th>
	<th>Bug ID</th>
	<th>Log</th>
	<th><a href="?{% buildsortqs "last_built" %}" title="Sort packages by last built">Last Built</a></th>
	<th>Arch SVN</th>
	<th>Arch PKG</th>
{% if user.is_authenticated %}
	<th>Rebuild</th>
	<th>Load Bug</th>
{% endif %}
	</tr>
    {% for r in object_list %}
		<tr>
		<td>{{r.repo.name}}</td>
        <td><a href="{% url 'package' r.repo.name r.package %}">{{ r.package }}</a></td>
		<td><span {% if r.flagged %}style="color:red"{% endif %}>{{r.status | status}}</span></td>
		<td>{{r.bug_id | link_bug}}</td>
		<td><a href="{% url 'log' r.repo.name r.package %}">Log</a></td>
		<td>{{r.last_built}}</td>
		<td><a href="https://projects.archlinux.org/svntogit/{{ r.repo.svn_path }}.git/log/trunk?h=packages/{{r.package}}">Arch SVN</a></td>
		<td><a href="https://www.archlinux.org/packages/{{r.repo.name}}/x86_64/{{r.package}}">Arch PKG</a></td>
{% if user.is_authenticated %}
		<td><a href="{% url 'rebuild' r.repo.name r.package %}">Rebuild</a></td>
		<td><a href="{% url 'load_bug' r.repo.name r.package %}">Load Bug</a></td>
{% endif %}
		</tr>
    {% endfor %}
    </table>
{% if is_paginated %}
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}&amp;{{current_query}}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}&amp;{{current_query}}">next</a>
        {% endif %}
    </span>
</div>
{% endif %}
{% else %}
    <p>No packages.</p>
{% endif %}
{% endblock %}

results/templates/login.html
{% extends "base.html" %}

{% block content %}
<form method="post">{% csrf_token %}
	<fieldset>
		<legend>Enter login credentials</legend>
		{{ form.as_p }}
		<p><label></label> <input type="submit" value="Login" /></p>
	</fieldset>
</form>
{% endblock %}

results/templates/package.html
{% extends "base.html" %}

{% block content %}

<a href="{{r.jenkins_id | jenkins_url}}/console">Jenkins</a><br>
<a href="https://bugs.archlinux.org/?project=1&amp;cat%5B%5D=2&amp;string={{r.package}}">Bug Reports</a><br>
{% if user.is_authenticated %}
	<a href="{% url 'rebuild' r.repo.name r.package %}">Rebuild</a><br>
	<a href="{% url 'edit' r.repo.name r.package %}">Edit</a><br>
	<a href="{% url 'load_bug' r.repo.name r.package %}">Load</a><br>
{% endif %}
<a href="https://www.archlinux.org/packages/{{r.repo.name}}/{% if a.arch %}{{r.arch}} {% else %}x86_64{%endif%}/{{r.package}}/">Arch Package</a><br>
Build status: {{ r.status | status }} <br>
Bug ID: {{ r.bug_id | link_bug}}<br>
Average Build Time: {{avg}}<br>

<table>
<tr><th>Length</th><th>Date</th><th>Log</th><th>Status</th><th>Data</th><th>Size</th></tr>
{% for b in builds %}
<tr>
	<td>{{b.length}}</td>
	<td>{{b.time}}</td>
	<td><a href="{% url 'log' r.repo.name r.package %}">Log</a></td>
	<td>{{b.status | status}}</td>
	<td>{{b.data}}</td>
	<td>{{b.size}}</td>
</tr>
{% endfor %}
</table>

{% endblock %}